version: 2
updates:
  # Configuration for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'bukhalo'
    assignees:
      - 'bukhalo'
    open-pull-requests-limit: 5
